site_name: SupportPro Hub

nav:
  - Home: index.md
  - 1. Introduction: 1.md
  - 2. Customer Communication: 2.md
  - 3. Problem Solving For Customers: 3.md
  - 4. Dealing with Difficult Customers: 4.md
  - 5. Effective Communication Techniques: 5.md
  - 6. Customer Service Basics: 6.md
  - 7. Empathy Training: 7.md
  - 8. Building Rapport with Customers: 8.md
  - 9. Problem Solving frameworks: 9.md
  - 10. Time Management for Customer Service: 10.md
  - 11. Effective use of technology: 11.md
  - 12. Conflict Resolution Skills: 12.md
  - 13. Adapting to changing consumer preferences: 13.md
  - 14. Handling customer inquires: 14.md
  - 15. Customer Feedback Management: 15.md
  - 16. Team Collaboration in Customer Service: 16.md
  - 17. Crisis Management Training: 17.md
  - 18. Positive Language and Phrasing: 18.md
  - 19. Multi-Channel Customer Service: 19.md
  - 20. Cultural Sensitivity Training: 20.md
  - 21. Setting Customer Expectations: 21.md
  - 22. Customer Retention Strategies: 22.md
  - 23. Advanced Communication Techniques: 23.md
  - 24. Innovative Customer Service Practices: 24.md
  - 25. Self-Care for Customer Service Representatives: 25.md
  - 26. Continuous Professional Development: 26.md

theme:
  name: material
  features:
    - header.autohide
    - navigation.footer
    - toc.follow

  toggle:
     icon: material/theme-light-dark
     name: Switch to light-mode
  
  palette:
     # Toggle light mode
    - scheme: slate
      primary: yellow
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Toggle dark mode
    - scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  font:
    text: Roboto
    code: "Fira Code"
  
  icon:
     logo: material/library-outline
  
  markdown_extensions: 
  - attr_list
  - md_in_html

